### ISSUE TITLE
Não buscar cotações em feriados

### ISSUE THREAD

**Issue by leogregianin** [open-bacen/cotacao-diaria-dolar#5]
Não buscar cotações em feriados Nacionais, do Estado de São Paulo e da cidade de São Paulo.

https://github.com/peopledoc/workalendar
https://github.com/dr-prodigy/python-holidays

**Comment by tuxo** [comment]
Oi! Gostaria de ajudar nesta issue!

**Comment by leogregianin** [comment]
@tuxo, obrigado pela ajuda.
