### ISSUE TITLE
Buscar cotações por período

### ISSUE THREAD

**Issue by leogregianin** [open-bacen/cotacao-diaria-dolar#6]
https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/documentacao

**Comment by MatheusMuriel** [comment]
Ola! Muito interessante o seu projeto. Eu posso fazer essa Issue 
Vc pode atribuir ela a mim?

**Comment by MatheusMuriel** [comment]
Feito! Assim que o merge for realizado eu posso implementar a passagem de parametros que eu comentei na descrição da PR

**Comment by leogregianin** [comment]
Obrigado pela contribuição @MatheusMuriel.
Vou enviar-lhe um convite para aderir à org! Todos que contribuem ao projeto estão convidados.
Ainda não temos um guidelines a seguir mas o que prevalece é o bom senso e o respeito.
